### PR TITLE
Add Ubuntu 20.04 LTS support

### PR DESCRIPTION
**Pull request by joncfoo**
First time doing this ... I think I followed all directions =]

Hope this builds :crossed_fingers:

### CODE REVIEW

**Comment by stevenolen** [comment]
rspm has been doing most of the maintenance of this repo so i've removed myself as reviewer for now!

**Comment by joncfoo** [comment]
Thanks @glin!  I added ubuntu 20 to the ignore list for the zlib build bug.

I ran into the same issue you saw where a build was hanging on `byte-compiling package 'grDevices'`, - I did see 1 CPU at 100% utilization though.

**Comment by jeroen** [comment]
https://demo.rstudiopm.com/all/__linux__/focal/latest/src/contrib/PACKAGES 💔 404

**Comment by joncfoo** [comment]
@jeroen, Ubuntu 20 support will be arriving soon :)

**Comment by jeroen** [comment]
I see the index is online now, is this ready to use? Or still experimental?

**Pull request merged**
