### PR TITLE
Add Fedora 41, remove Fedora 38

### PR DESCRIPTION
**Pull request by gaborcsardi**
Fedora 38 was EOL on 2024-05-21.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
R 3.0.0 - R 3.0.2 will fail:
https://github.com/rstudio/r-builds/actions/runs/11659477006

It is a known issue, that we cannot easily patch because it is in a recommended package:
https://github.com/rstudio/r-builds/pull/228#pullrequestreview-2089413547

**Review by glin — APPROVED** [review]
Looks good, thanks! I'll kick off a rebuild when this gets deployed, but that might have to wait until tomorrow.

**Comment by glin** [comment]
Well, nevermind, main Jenkins CI is apparently failing from some Node/npm version issue right now.

**Comment by gaborcsardi** [comment]
@glin When/if Jenkins is back, can you please start the builds? Thanks!

**Comment by glin** [comment]
@gaborcsardi All done, except for a failed 3.2.2 build which I'm rerunning now. Let me know if you notice any other missing R version though.

**Pull request merged**
