### PR TITLE
Support arm64 builds

### PR DESCRIPTION
**Pull request by gaborcsardi**
This is currently experimental. Right now it does work fine on my arm64 Macbook, but probably more changes are needed for building arm64 packages on our CI and for deployment, and docs as well.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Related: #149.

**Comment by gaborcsardi** [comment]
Actually, it doesn't work yet, the final deb/rpm package is not marked as arm64 currently.

**Comment by gaborcsardi** [comment]
OK, it works now I checked some RPM and DEB packages manually.

**Comment by gaborcsardi** [comment]
I build arm64 packages for a bunch of R versions. They are here: https://github.com/r-hub/R/releases

IDK if we want to make arm64 packages "official" and/or if we want to move them to our storage space.

Nevertheless, these packages are pretty useful for me and potentially others with an arm64 laptop.

**Review by glin — APPROVED** [review]
Looks good to me. I wonder why the GitHub Actions didn't run though, hmm. Probably because this is from a fork and the config doesn't have `on.pull_request`, https://github.com/rstudio/r-builds/blob/1a4f8a8fb3f0a3787e4ab6a54d4268791edfde05/.github/workflows/test.yml#L3-L4. I'll run it here just to double check the amd64 builds: https://github.com/rstudio/r-builds/compare/feature/arm64-pr?expand=1

For making the arm64 packages official, we don't have it in our platform support yet, but I think it's definitely coming as customer requests have been picking up, and IDE/Workbench is starting to provide arm64 builds now. 

As for CI and deployment, I think there are more open questions around that. I'd guess that getting arm64 builds into the existing AWS infrastructure would work, but take some effort to figure out. We'll need to build the Docker images for arm64 in Jenkins, and then get Batch jobs running on the arm64 graviton instances probably. Or perhaps we want to start migrating to GitHub Actions (e.g. for https://github.com/rstudio/r-builds/issues/7), which I bet would be much easier as the docker actions already support cross-platform building.

For storage, the existing S3 buckets seem fine, and I believe we're also going to eventually (soon?) push these binaries to DEB/RPM repos on Cloudsmith.

**Comment by gaborcsardi** [comment]
> which I bet would be much easier as the docker actions already support cross-platform building.

It is indeed not too bad to set this up, e.g. https://github.com/r-hub/r-minimal has arm64 builds: 
https://github.com/r-hub/r-minimal/actions/runs/3899975536/workflow#L58-L62
https://github.com/r-hub/r-minimal/actions/runs/3899975536/workflow#L81-L88
and this already pushes to Docker hub and ghcr.io:
https://github.com/r-hub/r-minimal/actions/runs/3899975536/workflow#L45-L56

The only issue is that they are very slow, it takes almost an hour to build this very minimal version of R. Nevertheless it probably makes sense to set up a GHA workflow to do the daily `next` and `devel` arm64 builds on GHA and then publish them at https://github.com/r-hub/R/releases for now.

**Comment by gaborcsardi** [comment]
@glin Thanks for the review!

**Pull request merged**
