### PR TITLE
Fix R-devel compilation on OpenSUSE

### PR DESCRIPTION
**Pull request by gaborcsardi**
By using newer compilers.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Needs a fix, obviously.

**Review by glin — APPROVED** [review]
Looks good, but are you getting this BLAS/LAPACK compilation error that I ran into a while back? https://github.com/rstudio/r-builds/issues/153#issuecomment-1379540584
```sh
gcc-8 -shared -fopenmp -L/usr/local/lib -o libRlapack.so dlamch.o dlapack.o cmplx.o dlartg.o dlassq.o la_constants.o la_xisnan.o zlartg.o zlassq.o   -L"../../../lib" -lRblas -lgfortran -lm -lquadmath 
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: zlassq.o: warning: relocation against `__la_xisnan_MOD_disnan' in read-only section `.text'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: dlassq.o: relocation R_X86_64_PC32 against symbol `__la_xisnan_MOD_disnan' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:104: libRlapack.so] Error 1
```
I still hit that error when testing these changes on openSUSE 15.3 and 15.4. I was hoping this would be fixed with the newer gcc, but it seems like a different issue.

**Comment by gaborcsardi** [comment]
Interesting, I was actually using this patch for the arm64 builds, and there are no errors there... seems like an x86_64 issue maybe?

**Comment by gaborcsardi** [comment]
Also, I don't really follow what is linking to what when the error happens, which library needs to be recompiled with `-fPIC`?

**Comment by gaborcsardi** [comment]
It is a bug in R, I think. I reported it, but it is also not hard to fix it, I believe.

**Comment by gaborcsardi** [comment]
Let's wait a couple of days with this, if they fix the bug in R-core, then we can just merge it as it. Otherwise we can patch the R sources to fix it.

**Comment by glin** [comment]
Sounds good, thanks for looking into that!

**Comment by gaborcsardi** [comment]
OK, this should fix the devel build as well. The patch is applied on all platforms, but it is the right thing to do, anyway.

Btw. do we want to run the 'next' and 'devel' builds on the CI for PRs?

**Review by glin — APPROVED** [review]

**Comment by glin** [comment]
About running next and devel builds on CI, sure, that sounds like a good idea. I didn't add devel originally because it could be failing for unrelated reasons, but I guess that shouldn't hold up merging PRs anyway. It'd be really useful for testing changes like this.

**Comment by gaborcsardi** [comment]
Thanks for reviewing this!

**Pull request merged**
