### PR TITLE
Add Fedora 40 patches for R 3.0.0 - R 4.0.2

### PR DESCRIPTION
**Pull request by gaborcsardi**
Hopefully this fixes all of them. I haven't actually tried to build all versions, but tried to apply the patches, and ran `./configure` on a bunch of them.

### CODE REVIEW

**Review by glin — APPROVED** [review]
Looks good. I checked the builds for 3.1.3, 3.2.5, 3.3.3, 3.4.4, 3.5.3, 3.6.3, 4.0.0 and they all worked. There was actually a separate issue for 3.0.2 and below, but those are so old that it's totally fine if we want to ignore them:
```
   21 | #define printf Rprintf
      |                ^~~~~~~
colamd_global.c:22:44: note: in expansion of macro ‘printf’
   22 | int (*colamd_printf) (const char *, ...) = printf ;
      |                                            ^~~~~~
make[5]: *** [/tmp/R-3.0.0/etc/Makeconf:123: colamd_global.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/tmp/RtmpP2glbB/R.INSTALLd24ae1b877c/Matrix/src/COLAMD/Source'
make[4]: *** [Makefile:3: library] Error 2
make[4]: Leaving directory '/tmp/RtmpP2glbB/R.INSTALLd24ae1b877c/Matrix/src/COLAMD'
make[3]: *** [Makevars:27: sublibraries] Error 1
make[3]: Leaving directory '/tmp/RtmpP2glbB/R.INSTALLd24ae1b877c/Matrix/src'
ERROR: compilation failed for package ‘Matrix’
* removing ‘/tmp/R-3.0.0/library/Matrix’
make[2]: *** [Makefile:51: Matrix.ts] Error 1
make[2]: Leaving directory '/tmp/R-3.0.0/src/library/Recommended'
make[1]: *** [Makefile:39: recommended-packages] Error 2
make[1]: Leaving directory '/tmp/R-3.0.0/src/library/Recommended'
make: *** [Makefile:74: stamp-recommended] Error 2
```
If so, you can just merge this and I'll redeploy/rebuild.

**Comment by gaborcsardi** [comment]
That is harder to fix, unfortunately, because it is in a recommended package, and recommended packages are included as `.tar.gz`, and we can't easily patch that.

**Comment by glin** [comment]
Okay, let's just ignore that for now. Those are very very old versions anyway.

**Comment by glin** [comment]
Ignoring the flaky opensuse build failures..

**Comment by glin** [comment]
Reran the failed builds and all versions are up now, besides the R <= 3.0.2 ones we're ignoring.

**Pull request merged**
